export const TRAER_TODOS = "TRAER_TODOS_POSTS";
export const TRAER_POSTS_POR_USUARIO = "TRAER_POSTS_POR_USUARIO";
export const AGREGAR_COMENTARIOS = "AGREGAR_COMENTARIOS";
export const ABRIR_CERRAR_MODAL = "ABRIR_CERRAR_MODAL";
export const CARGANDO = "CARGANDO_POSTS";
export const ERROR = "ERROR_POSTS";
